name = "KenkuKraft"
author = "Furglitch"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6452df1cfddc6c8052790f084c0154b882794731a78bc892c3063b26946d2a12"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.179"

[options]
acceptable-game-versions = ["fabric"]
